const BACKEND_URL="https://nrx-backend-2.onrender.com",SESSION_STORAGE_KEY="nrx_session_id",LOCAL_PROGRESS_KEY="nrxMiningData",DAILY_LIMIT=20,BASE_MINING_SPEED=20,MINING_RATE=.00139,OGADS_DIRECT_LINK="https://redirectapps.org/cl/i/j76pvj";let sessionId=null,minedTokens=0,miningSpeed=BASE_MINING_SPEED,isMining=!1,miningInterval=null,completedTasks=[],pendingWithdrawal=null,pendingBoostId=null,miningTimeLeft=300,timerMiningActive=!1,miningTimer=null,miningStartTime=null,ogadsForceLock=!1,uiElementsCache=null,lastSaveTime=0;
(function(){loadLocalProgress(),setupEventListeners(),updateUI(),startGlobalCountdown(),setInterval(saveLocalProgress,3e4),window.addEventListener("beforeunload",saveLocalProgress)})();
function loadLocalProgress(){try{const e=localStorage.getItem(LOCAL_PROGRESS_KEY);if(e){const t=JSON.parse(e);minedTokens=parseFloat(t.minedTokens)||0,miningSpeed=parseInt(t.miningSpeed)||BASE_MINING_SPEED,completedTasks=t.completedTasks||[],sessionId=t.sessionId||`local-${Date.now()}`}}catch(e){console.error(e)}}
function saveLocalProgress(){try{localStorage.setItem(LOCAL_PROGRESS_KEY,JSON.stringify({minedTokens,miningSpeed,completedTasks,sessionId,lastSave:Date.now()}))}catch(e){console.error(e)}}
function handleStartMining(){if(ogadsForceLock)return alert("Please complete the current task first!");if(minedTokens>=DAILY_LIMIT)return alert("Daily limit reached");isMining||timerMiningActive?stopMining():startMiningWithTimer()}
function startMiningWithTimer(){timerMiningActive=!0,isMining=!0,miningTimeLeft=300,miningStartTime=Date.now(),updateMiningButton(!0),startActualMining(),startCountdownTimer()}
function startActualMining(){miningInterval&&clearInterval(miningInterval),miningInterval=setInterval(()=>{if(!isMining||ogadsForceLock)return;const e=miningSpeed/20*MINING_RATE;minedTokens=Math.min(minedTokens+e,DAILY_LIMIT),updateUI(),minedTokens>=DAILY_LIMIT&&(stopMining(),showNotification("🎉 Daily limit reached","success"))},1e3)}
function startCountdownTimer(){miningTimer&&clearInterval(miningTimer),miningTimer=setInterval(()=>{if(!timerMiningActive||ogadsForceLock)return;miningTimeLeft--,updateTimerDisplay(),miningTimeLeft<=0&&(clearInterval(miningTimer),miningTimer=null,stopMining(),openOGAdsLocker("timer"))},1e3)}
function stopMining(){isMining=!1,timerMiningActive=!1,miningInterval&&clearInterval(miningInterval),miningTimer&&clearInterval(miningTimer),updateMiningButton(!1),saveLocalProgress()}
function updateTimerDisplay(){const e=document.getElementById("mining-timer"),t=document.getElementById("mining-progress");e&&(e.textContent=formatTime(miningTimeLeft)),t&&(t.style.width=(300-miningTimeLeft)/3+"%")}
function formatTime(e){const t=Math.floor(e/60),n=e%60;return`${String(t).padStart(2,"0")}:${String(n).padStart(2,"0")}`}
function updateUI(){uiElementsCache||(uiElementsCache={minedEl:document.getElementById("mined-tokens"),speedEl:document.getElementById("mining-speed"),availEl:document.getElementById("available-tokens"),withdrawalAmountEl:document.getElementById("withdrawal-amount"),currentSpeedEl:document.getElementById("current-speed")});const e=uiElementsCache;e.minedEl&&(e.minedEl.textContent=minedTokens.toFixed(4)+" NRX"),e.speedEl&&(e.speedEl.textContent=miningSpeed+" H/s"),e.availEl&&(e.availEl.textContent=minedTokens.toFixed(4)),e.currentSpeedEl&&(e.currentSpeedEl.textContent=miningSpeed),e.withdrawalAmountEl&&(e.withdrawalAmountEl.value=minedTokens.toFixed(4)),updateTaskVisuals()}
function updateMiningButton(e){const t=document.getElementById("start-mining-btn");if(!t)return;e?(t.innerHTML='<i class="fas fa-pause"></i> Stop Mining',t.classList.replace("btn-primary","btn-warning")):(t.innerHTML='<i class="fas fa-play"></i> Start Mining Now',t.classList.replace("btn-warning","btn-primary"),document.getElementById("mining-timer").textContent="05:00",document.getElementById("mining-progress").style.width="0%"),t.disabled=ogadsForceLock}
function updateTaskVisuals(){document.querySelectorAll(".task").forEach(e=>{const t=e.getAttribute("data-task");completedTasks.includes(`task-${t}`)&&(e.style.pointerEvents="none",e.style.background="linear-gradient(90deg,#27ae60,#2ecc71)",e.style.color="#fff",e.innerHTML='<i class="fas fa-check-circle"></i><h4>Task Completed</h4><p>Already boosted</p>')})}
function setupEventListeners(){document.getElementById("start-mining-btn")?.addEventListener("click",handleStartMining),document.getElementById("mine-now-btn")?.addEventListener("click",handleBoostMining),document.getElementById("withdraw-btn")?.addEventListener("click",handleWithdraw),document.querySelectorAll(".task").forEach(e=>e.addEventListener("click",()=>handleTaskClick(e.getAttribute("data-task")))),document.getElementById("confirm-withdrawal")?.addEventListener("click",handleConfirmWithdrawal)}
function handleBoostMining(){if(ogadsForceLock)return alert("Complete the current task first!");if(!isMining)return alert("Start mining first");openOGAdsLocker("boost")}
function handleWithdraw(){if(ogadsForceLock)return alert("Complete the current task first!");if(minedTokens<.001)return alert("Minimum withdrawal is 0.001 NRX");document.getElementById("withdrawal-modal").style.display="block"}
function handleTaskClick(e){completedTasks.includes(`task-${e}`)||((pendingBoostId=e),openOGAdsLocker("task"))}
function handleConfirmWithdrawal(){const e=document.getElementById("wallet-address").value.trim(),t=parseFloat(document.getElementById("withdrawal-amount").value);if(!e.startsWith("0x")||42!==e.length)return alert("Invalid address");if(t>minedTokens)return alert("Amount exceeds balance");if(t<.001)return alert("Minimum withdrawal");minedTokens-=t,updateUI(),saveLocalProgress(),document.getElementById("withdrawal-modal").style.display="none",showNotification("Withdrawal initiated","success")}
function openOGAdsLocker(e){stopMining(),saveLocalProgress(),ogadsForceLock=!0,updateMiningButton(!1);const t=document.createElement("div");t.id="ogads-container",t.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;background:#000;z-index:99999;display:flex;flex-direction:column";const n=document.createElement("iframe");n.src=OGADS_DIRECT_LINK,n.style.cssText="flex:1;width:100%;border:none",t.appendChild(n),document.body.appendChild(t)}
function applyOGAdsReward(e){if("timer"===e)setTimeout(startMiningWithTimer,1e3);else if("boost"===e){miningSpeed+=15,updateUI(),setTimeout(()=>{miningSpeed-=15,updateUI()},36e5)}else if("task"===e&&pendingBoostId){const t={1:5,2:10,3:15,4:20,5:8,6:12}[pendingBoostId]||10;miningSpeed+=t,completedTasks.push(`task-${pendingBoostId}`),pendingBoostId=null}updateUI()}
function startGlobalCountdown(){setInterval(()=>{},1e3)}
function showNotification(e,t){const n=document.createElement("div");n.innerText=e,n.style.cssText="position:fixed;bottom:20px;right:20px;background:#2ecc71;color:#fff;padding:12px;border-radius:8px;z-index:99999",document.body.appendChild(n),setTimeout(()=>n.remove(),3e3)}
window.addEventListener("error",saveLocalProgress);
